name: Build Image

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Build Docker Container
      run: docker build -t resume-env:latest .

    - name: Compile PDF
      run: docker run -v "$(pwd)/shared/output:/build/output" resume-env:latest ./build.sh

    - name: Test
      run: ls shared/output
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Austin_Wolf-resume
        path: shared/output/*

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: shared/output/Austin_Wolf-resume.pdf
