name: Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Build Docker Container
      run: docker build -t resume-env:latest .

    - name: Compile PDF
      run: docker run -v "$(pwd)/shared/output:/build/shared" resume-env:latest ./build.sh

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Austin_Wolf-resume
        path: shared/output
