name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t resume-env:latest .
    - name: Run the Build
      run: docker run  --name resume-cont resume-env:latest
    - name: Copy contents from container
      run: |
        docker cp resume-cont:/build/output shared/
    - name: Upload data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Austin_Wolf-resume
        path: shared/output